//! Bounty-report export for Vega findings.
//!
//! Deterministic, model-free, fully offline. Produces two formats:
//! - **SARIF 2.1.0** — ingestible by GitHub code scanning, DefectDojo, etc.
//! - **Markdown** — paste-ready bug-bounty / pentest report.

use crate::vega::model::{Alert, Severity};
use serde_json::{json, Value};

/// Map our severity to a SARIF `level`. SARIF only has error/warning/note, so
/// we collapse critical+high → error and keep the real severity in properties.
fn sarif_level(sev: Severity) -> &'static str {
    match sev {
        Severity::Critical | Severity::High => "error",
        Severity::Medium => "warning",
        Severity::Low | Severity::Info => "note",
    }
}

/// Build a SARIF 2.1.0 document from a set of alerts.
pub fn to_sarif(target: &str, alerts: &[Alert], triage: &[String]) -> Value {
    let rules: Vec<Value> = {
        let mut seen = std::collections::BTreeSet::new();
        alerts
            .iter()
            .filter(|a| seen.insert(a.type_key.clone()))
            .map(|a| {
                json!({
                    "id": a.type_key,
                    "name": a.title,
                    "shortDescription": { "text": a.title },
                    "defaultConfiguration": { "level": sarif_level(a.severity) },
                    "properties": { "security-severity": security_severity(a.severity) }
                })
            })
            .collect()
    };

    let results: Vec<Value> = alerts
        .iter()
        .enumerate()
        .map(|(i, a)| {
            let verdict = triage.get(i).cloned().unwrap_or_default();
            let mut props = serde_json::Map::new();
            props.insert("severity".into(), json!(a.severity.as_str()));
            if !verdict.is_empty() {
                props.insert("aiTriage".into(), json!(verdict));
            }
            if let Some(dt) = &a.detection_type {
                props.insert("detectionType".into(), json!(dt));
            }
            json!({
                "ruleId": a.type_key,
                "level": sarif_level(a.severity),
                "message": { "text": format!("{}\n{}", a.title, a.output) },
                "locations": [{
                    "physicalLocation": {
                        "artifactLocation": { "uri": a.resource }
                    }
                }],
                "properties": Value::Object(props)
            })
        })
        .collect();

    json!({
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "HADES Vega DAST",
                    "informationUri": "https://github.com/subgraph/Vega",
                    "version": "1.0.0",
                    "rules": rules
                }
            },
            "automationDetails": { "id": format!("vega-scan/{target}") },
            "results": results
        }]
    })
}

/// SARIF `security-severity` is a 0.0–10.0 string (CVSS-like). Approximate.
fn security_severity(sev: Severity) -> &'static str {
    match sev {
        Severity::Critical => "9.5",
        Severity::High => "8.0",
        Severity::Medium => "5.5",
        Severity::Low => "3.0",
        Severity::Info => "0.5",
    }
}

/// Build a paste-ready Markdown report.
pub fn to_markdown(target: &str, alerts: &[Alert], triage: &[String]) -> String {
    let mut counts = [0usize; 5]; // info, low, medium, high, critical
    for a in alerts {
        counts[a.severity as usize] += 1;
    }

    let mut md = String::new();
    md.push_str(&format!("# Security Findings — {target}\n\n"));
    md.push_str(&format!(
        "**{} findings** · {} critical · {} high · {} medium · {} low · {} info\n\n",
        alerts.len(),
        counts[Severity::Critical as usize],
        counts[Severity::High as usize],
        counts[Severity::Medium as usize],
        counts[Severity::Low as usize],
        counts[Severity::Info as usize],
    ));
    md.push_str("> Generated by HADES Vega DAST. Authorized testing only.\n\n");

    if alerts.is_empty() {
        md.push_str("_No findings on crawled parametric paths._\n");
        return md;
    }

    md.push_str("## Summary\n\n| # | Severity | Type | Resource | Triage |\n|---|---|---|---|---|\n");
    for (i, a) in alerts.iter().enumerate() {
        let verdict = triage.get(i).map(String::as_str).unwrap_or("");
        md.push_str(&format!(
            "| {} | {} | {} | `{}` | {} |\n",
            i + 1,
            a.severity.as_str(),
            md_escape(&a.title),
            md_escape(&a.resource),
            verdict
        ));
    }
    md.push('\n');

    md.push_str("## Details\n\n");
    for (i, a) in alerts.iter().enumerate() {
        let verdict = triage.get(i).map(String::as_str).unwrap_or("");
        md.push_str(&format!(
            "### {}. {} ({})\n\n",
            i + 1,
            md_escape(&a.title),
            a.severity.as_str()
        ));
        md.push_str(&format!("- **Resource:** `{}`\n", md_escape(&a.resource)));
        if let Some(dt) = &a.detection_type {
            md.push_str(&format!("- **Detection:** {}\n", md_escape(dt)));
        }
        if !verdict.is_empty() {
            md.push_str(&format!("- **AI triage:** {verdict}\n"));
        }
        if !a.output.is_empty() {
            let ev: String = a.output.chars().take(800).collect();
            md.push_str(&format!("\n**Evidence:**\n\n```\n{}\n```\n", ev));
        }
        md.push('\n');
    }
    md
}

fn md_escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Vec<Alert> {
        vec![Alert {
            type_key: "vinfo-sql-inject".into(),
            title: "SQL Injection".into(),
            severity: Severity::High,
            resource: "/search?q=1".into(),
            key: "k".into(),
            output: "You have an error in your SQL syntax".into(),
            detection_type: Some("Differential".into()),
            request_id: None,
            response_id: None,
            extra: Default::default(),
            timestamp_ms: 0,
        }]
    }

    #[test]
    fn sarif_has_runs_and_results() {
        let s = to_sarif("https://x.com", &sample(), &["CONFIRMED".into()]);
        assert_eq!(s["version"], "2.1.0");
        assert_eq!(s["runs"][0]["results"][0]["ruleId"], "vinfo-sql-inject");
        assert_eq!(s["runs"][0]["results"][0]["level"], "error");
        assert_eq!(
            s["runs"][0]["results"][0]["properties"]["aiTriage"],
            "CONFIRMED"
        );
    }

    #[test]
    fn markdown_includes_summary_and_evidence() {
        let md = to_markdown("https://x.com", &sample(), &["CONFIRMED".into()]);
        assert!(md.contains("# Security Findings"));
        assert!(md.contains("SQL Injection"));
        assert!(md.contains("SQL syntax"));
        assert!(md.contains("CONFIRMED"));
    }

    #[test]
    fn markdown_handles_empty() {
        let md = to_markdown("https://x.com", &[], &[]);
        assert!(md.contains("No findings"));
    }
}
