/**
 * Kortex throughput tracker.
 *
 * Records per-completion telemetry (token counts + wall-clock durations) and
 * exposes a rolling-window aggregate. Used by the KortexInferencePanel "Live
 * Throughput" card and the RightSidebar inline tok/s indicator.
 *
 * Token counting strategy, in priority order:
 *   1. Backend-reported counts (the local backend: `eval_count` / `prompt_eval_count`;
 *      llama.cpp `/completion` final chunk: `tokens_predicted` /
 *      `tokens_evaluated`). These are ground truth.
 *   2. Approximation `chars / 4` (rule of thumb for English/code). Used when
 *      backend doesn't expose counts.
 *
 * History is bounded so a long session can't grow it forever. Recent entries
 * dominate the average so the visual responds to the last few requests, not
 * the cumulative history.
 */

export interface CompletionSample {
    /** Wall-clock ms from request send to last token. */
    wall_clock_ms: number;
    /** Wall-clock ms of the prefill phase only (TTFT). Optional. */
    prefill_ms?: number;
    /** Tokens generated by the decode phase. */
    output_tokens: number;
    /** Tokens consumed during prefill (input). */
    input_tokens: number;
    /** Backend that handled the request. */
    backend: string;
    /** Whether KDKVC reported a prefix hit on this request. */
    cache_hit: boolean;
    /** Number of tokens the KDKVC restored from disk for this request. */
    tokens_skipped: number;
    /** Identifier of the model that produced the response, when known. */
    model_id?: string;
    /** Unix ms when the sample was recorded. */
    ts_unix_ms: number;
}

export interface ThroughputSummary {
    /** Output tokens / decode_seconds for the most recent sample. */
    current_tps: number;
    /** Average across the rolling window of recent samples. */
    avg_tps: number;
    /** Average prefill rate (input_tokens / prefill_seconds), if any sample
     *  carried a prefill_ms field. NaN otherwise. */
    avg_prefill_tps: number;
    /** Cache hit rate over the rolling window. */
    cache_hit_rate: number;
    /** Number of samples in the window. */
    sample_size: number;
    /** Total tokens skipped via KDKVC across the window. */
    total_tokens_skipped: number;
    /** Most recent sample, for "last request: X tok / Y ms" lines. */
    last?: CompletionSample;
}

const DEFAULT_WINDOW_SIZE = 16;
const history: CompletionSample[] = [];

/**
 * Best-effort token count from a character count. Standard rule of thumb is
 * one token per 4 characters for English/code; tighter on natural language,
 * looser on whitespace-heavy code, but consistent enough for a live readout.
 */
export function approximateTokensFromChars(chars: number): number {
    if (!Number.isFinite(chars) || chars <= 0) return 0;
    return Math.max(1, Math.round(chars / 4));
}

/**
 * Record a completion. Safe to call from any service that streams a response.
 * Failures here must never escape into the inference path.
 */
export function recordCompletion(sample: CompletionSample): void {
    if (!Number.isFinite(sample.wall_clock_ms) || sample.wall_clock_ms <= 0) return;
    history.push(sample);
    while (history.length > DEFAULT_WINDOW_SIZE) {
        history.shift();
    }
}

/**
 * Snapshot the rolling-window summary. The "current" tok/s is always the most
 * recent sample, so the UI updates immediately after every request.
 */
export function summarizeThroughput(): ThroughputSummary {
    if (history.length === 0) {
        return {
            current_tps: 0,
            avg_tps: 0,
            avg_prefill_tps: Number.NaN,
            cache_hit_rate: 0,
            sample_size: 0,
            total_tokens_skipped: 0,
        };
    }
    const last = history[history.length - 1];
    const current_tps = computeTps(last.output_tokens, last.wall_clock_ms);

    let tps_sum = 0;
    let tps_count = 0;
    let prefill_sum = 0;
    let prefill_count = 0;
    let hits = 0;
    let skipped = 0;
    for (const s of history) {
        const tps = computeTps(s.output_tokens, s.wall_clock_ms);
        if (Number.isFinite(tps) && tps > 0) {
            tps_sum += tps;
            tps_count++;
        }
        if (s.prefill_ms && s.prefill_ms > 0 && s.input_tokens > 0) {
            const ptps = (s.input_tokens * 1000) / s.prefill_ms;
            if (Number.isFinite(ptps) && ptps > 0) {
                prefill_sum += ptps;
                prefill_count++;
            }
        }
        if (s.cache_hit) hits++;
        skipped += s.tokens_skipped || 0;
    }
    return {
        current_tps,
        avg_tps: tps_count > 0 ? tps_sum / tps_count : 0,
        avg_prefill_tps: prefill_count > 0 ? prefill_sum / prefill_count : Number.NaN,
        cache_hit_rate: hits / history.length,
        sample_size: history.length,
        total_tokens_skipped: skipped,
        last,
    };
}

/**
 * Compute tokens per second from a token count and a duration in ms.
 * Clamps tiny denominators to 1 ms so we don't divide by zero on instant
 * responses (cache full-hit replays).
 */
export function computeTps(tokens: number, wall_clock_ms: number): number {
    const ms = Math.max(1, wall_clock_ms);
    return (tokens * 1000) / ms;
}

/** Reset the rolling window. Exposed for tests; the production app keeps
 *  history alive for the lifetime of the renderer. */
export function __resetThroughputHistoryForTesting(): void {
    history.length = 0;
}

/** Format a tok/s value for compact display (e.g. status pills). */
export function formatTps(tps: number): string {
    if (!Number.isFinite(tps) || tps <= 0) return '--';
    if (tps >= 100) return `${Math.round(tps)} tok/s`;
    return `${tps.toFixed(1)} tok/s`;
}
