[package]
name = "aim-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
rand = "=0.8.5"
candle-core = "=0.7.1"
candle-nn = "=0.7.1"
candle-transformers = "=0.7.1"
image = "0.24"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
uuid = { version = "1.23.1", features = ["v4"] }
