model = "gpt-5.5"
model_reasoning_effort = "medium"

[marketplaces.openai-bundled]
last_updated = "2026-06-05T15:17:37Z"
source_type = "local"
source = '\\?\C:\Users\HADES\.codex\.tmp\bundled-marketplaces\openai-bundled'

[windows]
sandbox = "elevated"

[projects.'c:\users\hades\desktop\vscodium-rust']
trust_level = "trusted"

[plugins."browser-use@openai-bundled"]
enabled = true
