pub mod android;
pub mod content_provider;
pub mod crypto;
pub mod deeplink;
pub mod flutter;
pub mod ios;
pub mod logic_flaws;
pub mod mobsf_rules;
pub mod p12_cracker;
pub mod sdk_profiler;
pub mod shared;
pub mod ssl_pin;
pub mod storage_audit;
pub mod webview;

pub use android::{audit_dex_strings, audit_manifest, audit_network_security_config};
pub use content_provider::{audit_manifest_providers, audit_provider_source_code};
pub use crypto::audit_cryptography;
pub use deeplink::audit_deeplinks_and_intents;
pub use flutter::{audit_flutter_binary, FlutterAuditResult};
pub use ios::{audit_entitlements, audit_info_plist, check_macho_encryption};
pub use logic_flaws::audit_logic_flaws;
pub use mobsf_rules::scan_mobsf_rules;
pub use p12_cracker::{audit_p12_file, generate_p12_candidates};
pub use sdk_profiler::{audit_discovered_sdks, match_framework, match_package_or_string, SdkCategory, SdkInfo};
pub use shared::{extract_endpoints, is_hermes_bytecode, scan_secrets, shannon_entropy};
pub use ssl_pin::audit_ssl_pinning;
pub use storage_audit::{audit_android_storage, audit_ios_storage};
pub use webview::audit_webview_and_bridges;

